title: Cyberjutsu
email:
description: >-
  Sharing practical knowledge across topics like red teaming, threat hunting, and security research.

url: "https://gnarizard.github.io"
baseurl: "/cyberjutsu"
repository: "gnarizard/cyberjutsu"

twitter_username: mega_gnarizard
github_username: gnarizard
timezone: America/Los_Angeles

search: false

markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

permalink: /:categories/:title/

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "gnarizard"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Sharing practical knowledge across topics like red teaming, threat hunting, and security research."
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/mega_gnarizard"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gnarizard"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ryan7926"

footer:
  links:
    - label: "X"
      icon: "fab fa-fw fa-x-twitter"
      url: "https://twitter.com/mega_gnarizard"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gnarizard"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/ryan7926"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: "_pages"
      type: pages
    values:
      layout: site